//our users array. Each element contains a unique user id generated by socket.io, username, and his room
const users = [];

function addUser(id, username, room){
    const user = {id, username, room};
    users.push(user);
    return user;
}

//Get User by its id
function getUser(id){
    return users.find(user => user.id === id);
}

//remove the user from array on leaving
function userleft(id){
    const index = users.findIndex(user => user.id === id); 
    if(index != -1){        //That is user present in our array
        return users.splice(index,1)[0];    //return the user who left, and remove him
    }

}

//get alll users of a room
function getRoomUsers(room){
    return users.filter(user => user.room === room);
}

module.exports = {addUser, getUser, getRoomUsers, userleft};